name: keepchange

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --global user.email "coder2z@qq.com" && git config --global user.name "coder2z"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          date +"%Y-%m-%d %H:%M:%S.%N" > keepchange.txt
          git commit -am ":rocket:update keepchange.txt"
          git push
